# Copyright 2026 Asisteme.AI
# Licensed under the Apache License, Version 2.0.
"""
TuData — Project Schemas
=========================
Pydantic schemas for the consolidated ProjectDocument output.

This replaces or supplements ExtractedDocument when using the new
Content-First Parallel Pipeline — it carries structured tables and
figure analyses alongside text chunks.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class MissingFieldSeverity(str, Enum):
    CRITICAL = "critical"   # document cannot be used without this
    WARNING  = "warning"    # important but document is still usable
    INFO     = "info"       # nice to have


class MissingField(BaseModel):
    """Represents a field expected but not found in the document."""
    field_name:  str
    description: str
    severity:    MissingFieldSeverity = MissingFieldSeverity.WARNING


class LineItem(BaseModel):
    """A single line item from an invoice/quote."""
    item_no:     Optional[str] = None
    description: str
    quantity:    Optional[str] = None
    unit:        Optional[str] = None
    unit_price:  Optional[str] = None
    total:       Optional[str] = None
    notes:       Optional[str] = None


class ProjectSummary(BaseModel):
    """High-level project identification."""
    project_name:    Optional[str] = None
    project_number:  Optional[str] = None
    client:          Optional[str] = None
    vendor:          Optional[str] = None
    quote_number:    Optional[str] = None
    quote_date:      Optional[str] = None
    valid_until:     Optional[str] = None
    project_location: Optional[str] = None
    total_amount:    Optional[str] = None
    currency:        str = "USD"


class TechnicalSpec(BaseModel):
    """A named technical specification."""
    category:    str        # e.g. "electrical", "mechanical"
    parameter:   str        # e.g. "input_voltage"
    value:       str        # e.g. "480V 3Ø"
    unit:        Optional[str] = None


class TableResult(BaseModel):
    """Serialized table for the ProjectDocument."""
    block_id:   int
    page:       int
    caption:    Optional[str] = None
    headers:    list[str]     = Field(default_factory=list)
    rows:       list[dict[str, str]] = Field(default_factory=list)
    row_count:  int           = 0
    col_count:  int           = 0
    extraction_method: str    = "unknown"
    confidence: float         = 1.0


class FigureResult(BaseModel):
    """Serialized figure analysis for the ProjectDocument."""
    block_id:        int
    page:            int
    figure_type:     str            = "other"
    description:     str            = ""
    components:      list[str]      = Field(default_factory=list)
    technical_specs: dict[str, str] = Field(default_factory=dict)
    text_labels:     list[str]      = Field(default_factory=list)
    references:      list[str]      = Field(default_factory=list)
    confidence:      float          = 1.0


class ProjectDocument(BaseModel):
    """
    Top-level consolidated output of the Content-First Parallel Pipeline.

    Contains structured results from all 3 content streams plus
    the LLM-generated executive summary and validation results.
    """
    # Identity
    doc_id:       str
    source_path:  str
    page_count:   int
    project_type: str
    classification_confidence: float = 1.0
    doc_format:   str = "digital"

    # Executive summary (generated by Consolidator LLM)
    executive_summary: Optional[str] = None
    project_summary:   Optional[ProjectSummary] = None

    # Structured content from each stream
    tables:     list[TableResult]    = Field(default_factory=list)
    figures:    list[FigureResult]   = Field(default_factory=list)
    line_items: list[LineItem]       = Field(default_factory=list)
    tech_specs: list[TechnicalSpec]  = Field(default_factory=list)

    # Free text sections (ordered)
    text_sections: list[dict[str, Any]] = Field(
        default_factory=list,
        description="List of {'section': str, 'content': str, 'page': int}"
    )

    # Quality signals
    missing_fields:   list[MissingField] = Field(default_factory=list)
    quality_score:    float = 0.0
    processing_notes: list[str] = Field(default_factory=list)

    # Raw extraction fallback (legacy chunks)
    raw_chunks: list[dict[str, Any]] = Field(default_factory=list)
